apiVersion: v1
kind: Service
metadata:
  name: coroot-node-agent
  namespace: monitoring
spec:
  selector:
    app: coroot-node-agent
    app.kubernetes.io/instance: coroot
    app.kubernetes.io/name: node-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
