apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mediaserver.selectorLabels" . | nindent 8 }}
        app: jackett
    spec:
      initContainers:
        - name: config-jackett
          image: docker.io/ubuntu:groovy
          command: ["/init-jackett/init-jackett.sh"]
          volumeMounts:
            - mountPath: /init-jackett
              name: init-files-jackett
          {{- if .Values.global.jackett.volume }}
            - name: {{ .Values.global.jackett.volume.name }}
              mountPath: /jackett-config
          {{- else }}
            - name: mediaserver-volume
              mountPath: /jackett-config
              subPath: "{{ .Values.global.general.storage.subPaths.config }}/jackett/Jackett"
          {{- end }}
          securityContext:
            runAsUser: {{ .Values.global.general.puid }}
            runAsGroup: {{ .Values.global.general.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: jackett-config
          image: "{{ .Values.global.jackett.container.image }}:{{ .Values.global.jackett.container.tag | default .Values.global.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: {{ .Values.global.jackett.container.port }}
              path: {{ .Values.global.radarr.ingress.path }}/UI/Dashboard
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: jackett-port
              containerPort: {{ .Values.global.jackett.container.port }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.global.jackett.volume }}
            - name: {{ .Values.global.jackett.volume.name }}
              mountPath: /config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.global.general.storage.subPaths.config }}/jackett"
          {{- end }}
          {{- with .Values.global.jackett.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if not .Values.global.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.global.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.global.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.global.jackett.volume }}
        - name: {{ .Values.global.jackett.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.jackett.volume.name }}
        {{- end }}
        - name: init-files-jackett
          configMap:
            defaultMode: 493
            name: init-jackett-cm
      {{- with merge .Values.global.jackett.container.nodeSelector .Values.global.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.global.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.global.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}