apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mediaserver.selectorLabels" . | nindent 8 }}
        app: sabnzbd
    spec:
      initContainers:
        - name: config-sabnzbd
          image: docker.io/ubuntu:groovy
          command: ["/init-sabnzbd/init-sabnzbd.sh"]
          volumeMounts:
            - mountPath: /init-sabnzbd
              name: init-files-sabnzbd
          {{- if .Values.global.sabnzbd.volume }}
            - name: {{ .Values.global.sabnzbd.volume.name }}
              mountPath: /sabnzbd-config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/sabnzbd-config"
              subPath: "{{ .Values.global.general.storage.subPaths.config }}/sabnzbd"
          {{- end }}
          securityContext:
            runAsUser: {{ .Values.global.general.puid }}
            runAsGroup: {{ .Values.global.general.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: sabnzbd-config
          image: "{{ .Values.global.sabnzbd.container.image }}:{{ .Values.global.sabnzbd.container.tag | default .Values.global.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: {{ .Values.global.sabnzbd.ingress.path }}/wizard/
              port: {{ .Values.global.sabnzbd.container.port.http }}
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: sabnzbd-http
              containerPort: {{ .Values.global.sabnzbd.container.port.http }}
              protocol: TCP
            - name: sabnzbd-https
              containerPort: {{ .Values.global.sabnzbd.container.port.https }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.global.sabnzbd.volume }}
            - name: {{ .Values.global.sabnzbd.volume.name }}
              mountPath: /config
          {{- else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.global.general.storage.subPaths.config }}/sabnzbd"
          {{- end }}
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "{{ .Values.global.general.storage.subPaths.downloads }}"
          {{- with .Values.global.sabnzbd.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if not .Values.global.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.global.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.global.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.global.sabnzbd.volume }}
        - name: {{ .Values.global.sabnzbd.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.sabnzbd.volume.name }}
        {{- end }}
        - name: init-files-sabnzbd
          configMap:
            defaultMode: 493
            name: init-sabnzbd-cm
      {{- with merge .Values.global.sabnzbd.container.nodeSelector .Values.global.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.global.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.global.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}