apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mediaserver.selectorLabels" . | nindent 8 }}
        app: transmission
    spec:
      initContainers:
        - name: config-transmission
          image: docker.io/ubuntu:groovy
          command: ["/init-transmission/init-transmission.sh"]
          volumeMounts:
            - mountPath: /init-transmission
              name: init-files-transmission
          {{ if .Values.global.transmission.volume }}
            - name: {{ .Values.global.transmission.volume.name }}
              mountPath: /transmission-config
          {{ else }}
            - name: mediaserver-volume
              mountPath: "/transmission-config"
              subPath: "{{ .Values.global.general.storage.subPaths.config }}/transmission"
          {{ end }}
          securityContext:
            runAsUser: {{ .Values.global.general.puid }}
            runAsGroup: {{ .Values.global.general.pgid }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: transmission-config
          image: "{{ .Values.global.transmission.container.image }}:{{ .Values.global.transmission.container.tag | default .Values.global.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: {{ .Values.global.transmission.ingress.path }}/
              port: {{ .Values.global.transmission.container.port.utp }}
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: trans-port
              containerPort: {{ .Values.global.transmission.container.port.utp }}
              protocol: TCP
            - name: trans-peer-tcp
              containerPort: {{ .Values.global.transmission.container.port.peer }}
              protocol: TCP
            - name: trans-peer-udp
              containerPort: {{ .Values.global.transmission.container.port.peer }}
              protocol: UDP
          volumeMounts:
          {{ if .Values.global.transmission.volume }}
            - name: {{ .Values.global.transmission.volume.name }}
              mountPath: /config
          {{ else }}
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "{{ .Values.global.general.storage.subPaths.config }}/transmission"
          {{ end }}
            - name: mediaserver-volume
              mountPath: "/downloads"
              subPath: "{{ .Values.global.general.storage.subPaths.downloads }}"
          {{- with .Values.global.transmission.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{ if not .Values.global.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.global.general.storage.pvcName }}
        {{ else }}
        - name: mediaserver-volume
          {{- toYaml .Values.global.general.storage.volumes | nindent 10 }}
        {{ end }}
        {{ if .Values.global.transmission.volume }}
        - name: {{ .Values.global.transmission.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.transmission.volume.name }}
        {{ end }}
        - name: init-files-transmission
          configMap:
            defaultMode: 493
            name: init-transmission-cm
      {{- with merge .Values.global.transmission.container.nodeSelector .Values.global.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.global.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.global.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}