apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.global.plex.replicaCount }}
  selector:
    matchLabels:
      {{- include "mediaserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mediaserver.selectorLabels" . | nindent 8 }}
        app: plex
    spec:
      volumes:
        {{- if not .Values.global.general.storage.customVolume }}
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: {{ .Values.global.general.storage.pvcName }}
        {{- else }}
        - name: mediaserver-volume
          {{- toYaml .Values.global.general.storage.volumes | nindent 10 }}
        {{- end }}
        {{- if .Values.global.plex.volume }}
        - name: {{ .Values.global.plex.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.plex.volume.name }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          envFrom:
            - configMapRef:
                name: plex-config
          image: "{{ .Values.global.plex.container.image }}:{{ .Values.global.plex.container.tag | default .Values.global.general.image_tag }}"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: {{ .Values.global.plex.container.port }}
              path: "/"
            initialDelaySeconds: 20
            periodSeconds: 15
          ports:
            - name: plex-port
              containerPort: {{ .Values.global.plex.container.port }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.global.plex.volume }}
            - name: {{ .Values.global.plex.volume.name }}
              mountPath: /config
          {{- else }}
            - name: mediaserver-volume
              mountPath: /config
              subPath: "{{ .Values.global.general.storage.subPaths.config }}/plex"
          {{- end }}
            - name: mediaserver-volume
              mountPath: /movies
              subPath: "{{ .Values.global.general.storage.subPaths.movies }}"
            - name: mediaserver-volume
              mountPath: /tv
              subPath: "{{ .Values.global.general.storage.subPaths.tv }}"
          {{- with .Values.global.plex.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with merge .Values.global.plex.container.nodeSelector .Values.global.general.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.global.general.podDistribution "cluster" }}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      {{- else if eq .Values.global.general.podDistribution "spread" }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: {{ .Release.Name }}
      {{- end }}