apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.plex.service.type }}
  ports:
    - port: {{ .Values.global.plex.service.port }}
      targetPort: {{ .Values.global.plex.container.port }}
      protocol: TCP
      name: plex-port
{{ if eq .Values.global.plex.service.type "NodePort" }}
      nodePort: {{ .Values.global.plex.service.nodePort }}
{{ end }}
  selector:
    app: plex
---
{{ if .Values.global.plex.service.extraLBService }}
apiVersion: v1
kind: Service
metadata:
  name: plex-lb
  {{- with .Values.global.plex.service.extraLBAnnotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.global.plex.service.port }}
      targetPort: {{ .Values.global.plex.container.port }}
      protocol: TCP
      name: plex-port
  selector:
    app: plex
{{ end }}