# Default values for bitwarden-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
deployStrategy: RollingUpdate
host: &host "bitwarden.smigula.io"

image:
  repository: vaultwarden/server
  tag: 1.30.1
  pullPolicy: IfNotPresent
  # imagePullSecrets for accessing private registries
  # pullSecrets: regcred

global:
  postgresql:
    enabled: true
    auth:
      postgresPassword: ""
      username: "bitwarden"
      password: "BitwardenP@55"
      database: "bitwarden"
  smtp:
    enabled: false
    env:
      MAILNAME: smtp.smigula.io
      RELAY_HOST: smtp.sendgrid.com
      RELAY_PORT: 587
      RELAY_USERNAME: mitch.murphy@gmail.com
      RELAY_PASSWORD: SuperSecret

## https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
env:
  SIGNUPS_ALLOWED: true
  INVITATIONS_ALLOWED: true
  PUSH_ENABLED: true
  PUSH_INSTALLATION_ID: "0b416aa5-d219-4214-a17f-b0e301435b6e"
  PUSH_INSTALLATION_KEY: "rLs9F2DZXv2ccRejQ0zp"
  SENDS_ALLOWED: true
  SIGNUPS_VERIFY: true
  INVITATION_ORG_NAME: SmigWarden
  ## Yubico (Yubikey) Settings
  ## Set your Client ID and Secret Key for Yubikey OTP
  ## You can generate it here: https://upgrade.yubico.com/getapikey/
  ## You can optionally specify a custom OTP server
  # YUBICO_CLIENT_ID=11111
  # YUBICO_SECRET_KEY=AAAAAAAAAAAAAAAAAAAAAAAA
  # YUBICO_SERVER=http://yourdomain.com/wsapi/2.0/verify
  ## Mail specific settings, set SMTP_FROM and either SMTP_HOST or USE_SENDMAIL to enable the mail service.
  ## To make sure the email links are pointing to the correct host, set the DOMAIN variable.
  ## Note: if SMTP_USERNAME is specified, SMTP_PASSWORD is mandatory
  # SMTP_HOST=smtp.domain.tld
  # SMTP_FROM=vaultwarden@domain.tld
  # SMTP_FROM_NAME=Vaultwarden
  # SMTP_SECURITY=starttls # ("starttls", "force_tls", "off") Enable a secure connection. Default is "starttls" (Explicit - ports 587 or 25), "force_tls" (Implicit - port 465) or "off", no encryption (port 25)
  # SMTP_PORT=587          # Ports 587 (submission) and 25 (smtp) are standard without encryption and with encryption via STARTTLS (Explicit TLS). Port 465 (submissions) is used for encrypted submission (Implicit TLS).
  # SMTP_USERNAME=username
  # SMTP_PASSWORD=password
  # SMTP_TIMEOUT=15

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  loadBalancerIP:

ingress:
  enabled: true
  labels: {}
  ingressClassName: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - *host
  tls:
    - secretName: bitwarden-tls
      hosts:
        - *host

  # pathType is only for k8s >= 1.1=
  pathType: Prefix


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

deploymentAnnotations: {}

## Persist data to a persitent volume
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 800Mi
  #storageClass:
  #existingClaim: "bitwarden-pvc"
